---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/home/jin/dev/sap-cloud-cap-java/bookstore/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
